version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8889:50070"
    networks:
      - bigdata
    
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode4:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    environment:
      SERVICE_PRECONDITION: "namenode:8020 datanode:50070 datanode2:50070 datanode3:50070 datanode4:50070"
    env_file:
      - ./hadoop-hive.env
    networks:
      - bigdata
  
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "PYSPARK_PYTHON=python3"
      # - "constraint:node==<yourmasternode>"
    networks:
      - bigdata
    volumes: 
      - ./spark-env-sh:/spark/conf/spark-env.sh

  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_PYTHON=python3"
      # - "constraint:node==<yourworkernode>"
    networks:
      - bigdata
    volumes: 
      - ./spark-env-sh:/spark/conf/spark-env.sh
      
  spark-worker-2:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_PYTHON=python3"
      # - "constraint:node==<yourworkernode>"
    networks:
      - bigdata
    volumes: 
      - ./spark-env-sh:/spark/conf/spark-env.sh

  jupyter:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    networks: 
      - bigdata
    volumes: 
      - work:/home/jupyter/work

volumes:
  work:
  namenode:
  datanode:
  datanode2:
  datanode3:
  datanode4:

networks:
  bigdata: